# This workflow runs tests and linting on push and pull request events, using Python 3.11.5, Poetry and Pytest, pep8, flake8. The coverage must be more than 90%.
# run using node16
name: build
on: [push, pull_request]

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8
      - name: Check Docstring with flake8-docstring
        run: |
          poetry run flake8 --docstring-convention google
      - name: Test with pytest
        run: |
          poetry run pytest --cov=src --cov-report=xml
      - name: Report coverage
        run: |
          poetry run coverage report
          poetry run coverage xml
      - name: Check coverage is above 90%
        run: |
          poetry run coverage report --fail-under=90
  # Path: .github/workflows/test.yml
