# This YAML file defines a GitHub Actions workflow that runs a linter on Python code using PEP8, Python version 3.11.5, and Poetry. The workflow is triggered on push and pull request events. It runs on the latest version of Ubuntu. The workflow defines a job called "lint" that runs the linter. The job uses a matrix strategy to specify the Python version. The steps in the job include checking out the code, setting up Python, installing dependencies using Poetry, and running the linter using Flake8 and flake8-docstrings.

name: Linting
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8
      - name: Check Docstring with flake8-docstring
        run: |
          poetry run flake8 --docstring-convention google

  # Path: .github/workflows/linting.yml